parent_dir = "Experiments/tabddpm/res_bgm/uci_german"
real_data_path = "configuration/datasets/uci_german/"
num_numerical_features = 7
model_type = "resnet"
seed = 0
# device = "cuda:0"
device = "cpu"

[model_params]
num_classes = 2
is_y_cond = true

[model_params.rtdl_params]
n_blocks = 2
d_main = 3
d_hidden = 4
dropout_first = 0.25
dropout_second = 0.0

[diffusion_params]
num_timesteps = 1000
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 1000
lr = 0.001
weight_decay = 1e-05
batch_size = 4096

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[tabular_processor]
type = "bgm"

[sample]
num_samples = 1055
batch_size = 10000
seed = 0

[eval.type]
eval_model = "mlp"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
